'use strict';

/**
 * Initial schema. Matches the Sequelize models in src/model/ exactly.
 *
 * Generated by hand (not sequelize-cli auto-generate) so the migration
 * file is the readable, reviewable source of truth — the AI editing
 * the schema can read this file directly without instantiating models.
 *
 * Reviewers: every column here has a 1:1 counterpart in the model
 * file; keep both in lockstep when adding fields.
 */

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    // gen_random_uuid lives in pgcrypto on Postgres 13–. On 14+ it's
    // in the core, but enabling the extension is idempotent so we run
    // it unconditionally — keeps the migration portable across PG
    // versions Tarrs sandboxes might ship.
    await queryInterface.sequelize.query(
      'CREATE EXTENSION IF NOT EXISTS pgcrypto',
    );

    await queryInterface.createTable('users', {
      id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue: Sequelize.literal('gen_random_uuid()'),
      },
      email: {
        type: Sequelize.TEXT,
        allowNull: false,
        unique: true,
      },
      password_hash: {
        type: Sequelize.TEXT,
        allowNull: false,
      },
      created_at: {
        type: Sequelize.DATE,
        allowNull: false,
        defaultValue: Sequelize.literal('now()'),
      },
      updated_at: {
        type: Sequelize.DATE,
        allowNull: false,
        defaultValue: Sequelize.literal('now()'),
      },
    });

    await queryInterface.createTable('posts', {
      id: {
        type: Sequelize.UUID,
        primaryKey: true,
        defaultValue: Sequelize.literal('gen_random_uuid()'),
      },
      title: { type: Sequelize.TEXT, allowNull: false },
      body: { type: Sequelize.TEXT, allowNull: false },
      author_id: {
        type: Sequelize.UUID,
        allowNull: false,
        references: { model: 'users', key: 'id' },
        onDelete: 'CASCADE',
      },
      created_at: {
        type: Sequelize.DATE,
        allowNull: false,
        defaultValue: Sequelize.literal('now()'),
      },
      updated_at: {
        type: Sequelize.DATE,
        allowNull: false,
        defaultValue: Sequelize.literal('now()'),
      },
    });

    // Supports both the list-by-recent default and a per-author
    // dashboard filter without a separate (author_id) index.
    await queryInterface.addIndex('posts', ['author_id', 'created_at'], {
      name: 'posts_author_created_idx',
    });
  },

  async down(queryInterface) {
    await queryInterface.dropTable('posts');
    await queryInterface.dropTable('users');
  },
};
